title: The Art, Science, and Engineering of Programming
issn: 2473-7321
doi: 10.22152/programming-journal.org
host: http://programming-journal.org

description: The Art, Science, and Engineering of Programming journal is a
  fully refereed, open access, free, electronic journal. It welcomes papers on
  the art of programming, broadly construed.


#baseurl: /

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  footnote_backlink: ''

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


host: 0.0.0.0
# EOF
