title: The Art, Science, and Engineering of Programming
issn: 2473-7321
doi: 10.22152/programming-journal.org
host: http://programming-journal.org
baseurl: /

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  footnote_backlink: ''

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


host: 0.0.0.0
# EOF
