title: The Art, Science, and Engineering of Programming
issn: 2473-7321
host: http://programming-journal.org
baseurl: /

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


host: 0.0.0.0
# EOF
